import os
import sys
import platform

OS_NAME = platform.system();
LIB_DIR=os.environ['LIB_DIR'];
BIN_DIR=os.environ['BIN_DIR'];


env=DefaultEnvironment().Clone()
SOURCES=Glob('yps_progress_bar/*.c')+Glob('*.c')

# env['CC']=os.environ['CC'];
# env['CXX']=os.environ['CXX'];
# env['AR']=os.environ['AR'];
EXPORT_DEF=''
if OS_NAME == 'Windows' and os.environ['TOOLS_NAME'] == '':
  EXPORT_DEF = ' /DEF:"src/yps_progress_bar.def" '

if 'BUILD_SHARED' in os.environ and os.environ['BUILD_SHARED'] == 'True':
  LIBS=['awtk'];
  LINKFLAGS=env['LINKFLAGS'] + EXPORT_DEF 
  env.SharedLibrary(os.path.join(BIN_DIR, 'yps_progress_bar'), SOURCES, LIBS=LIBS, LINKFLAGS=LINKFLAGS);
else:
  # env.Library(os.path.join(LIB_DIR, 'yps_progress_bar'), SOURCES);
  LIBS=['awtk'];
  LINKFLAGS=env['LINKFLAGS'] + EXPORT_DEF 
  env.SharedLibrary(os.path.join(BIN_DIR, 'yps_progress_bar'), SOURCES, LIBS=LIBS, LINKFLAGS=LINKFLAGS);

