# Access plugins
################
 
# Uncomment if you wish to use the linux input layer event interface
module_raw input
 
# For other driver modules, see the ts.conf man page
 
# Filter plugins
################
# Uncomment if needed for devices that measure pressure
module pthres pmin=1
 
# Uncomment if needed to filter noise samples
module dejitter delta=50