import os
import sys
import platform

OS_NAME = platform.system();
LIB_DIR=os.environ['LIB_DIR'];
BIN_DIR=os.environ['BIN_DIR'];

env=DefaultEnvironment().Clone()
env.Append(CPPPATH=[os.path.abspath('spine-cpp/spine-cpp_3.8/include')])

SOURCES=Glob('spine-cpp/spine-cpp_3.8/src/spine/*.cpp')

env.Library(os.path.join(LIB_DIR, 'spine'), SOURCES);

