import os
import sys
import platform

OS_NAME = platform.system();
LIB_DIR=os.environ['LIB_DIR'];
BIN_DIR=os.environ['BIN_DIR'];
print('####################################################')
print(os.environ['LIB_DIR'])
print(os.environ['BIN_DIR'])
print('####################################################')

env=DefaultEnvironment().Clone()
env.Append(CPPPATH=['/home/wdp/workspace/carbit-widget-awtk/widgets/awtk-widget-yps-widget-ico-ex/src', '.'])

SOURCES=Glob('yps_widget_ico_ex/*.c')+Glob('*.c')+Glob('common_tool/*.c')

EXPORT_DEF=''
if OS_NAME == 'Windows' and os.environ['TOOLS_NAME'] == '':
  EXPORT_DEF = ' /DEF:"src/yps_widget_ico_ex.def" '

if 'BUILD_SHARED' in os.environ and os.environ['BUILD_SHARED'] == 'True':
  LIBS=['awtk'];
  LINKFLAGS=env['LINKFLAGS'] + EXPORT_DEF 
  env.SharedLibrary(os.path.join(BIN_DIR, 'yps_widget_ico_ex'), SOURCES, LIBS=LIBS, LINKFLAGS=LINKFLAGS);
else:
  # env.Library(os.path.join(LIB_DIR, 'yps_widget_ico_ex'), SOURCES);
  LIBS=['awtk'];
  LINKFLAGS=env['LINKFLAGS'] + EXPORT_DEF 
  env.SharedLibrary(os.path.join(BIN_DIR, 'yps_widget_ico_ex'), SOURCES, LIBS=LIBS, LINKFLAGS=LINKFLAGS);

